version = "0.0.0"

exclude = ""
include = "*.csv"

[[generators]]
type = "cocos"
enable = true
project = "."
output = "cocos"

[[generators]]
type = "unity"
enable = true
project = "."
output = "unity"
namespace = "DataTable"