// DataTableManager.ts
// Generated by XCell 0.2.0
// Edit time: 2026-04-11T04:57:14.929215500+00:00
// Data version: 1.0.0

{% for table in tables %}
import { {{ table.typing }} } from './{{ table.typing }}';
{% endfor %}

export class DataTableManager {
    private static instance: DataTableManager;
    {% for table in tables %}
    private {{ table.private_name }}: {{ table.typing }} | null = null;
    {% endfor %}

    private constructor() {}

    public static getInstance(): DataTableManager {
        if (!DataTableManager.instance) {
            DataTableManager.instance = new DataTableManager();
        }
        return DataTableManager.instance;
    }

    {% for table in tables %}
    public {{ table.public_name }}(): {{ table.typing }} {
        if (!this.{{ table.private_name }}) {
            this.{{ table.private_name }} = new {{ table.typing }}();
        }
        return this.{{ table.private_name }}!;
    }
    {% endfor %}

    public async init(): Promise<void> {
        // 初始化所有表格数据
        {% for table in tables %}
        const {{ table.private_name }}Data = await fetch('tables/{{ table.typing }}.json');
        const {{ table.private_name }}Json = await {{ table.private_name }}Data.json();
        {{ table.typing }}.init({{ table.private_name }}Json);
        {% endfor %}
    }
}

export const DataTable = DataTableManager.getInstance();
