[package]
name = "xcell-analyzer"
version = "0.2.0"
authors = { workspace = true }
description = "XCell analyzer library"
repository = "https://github.com/oovm/XCell"
documentation = "https://docs.rs/xcell-analyzer"
license = { workspace = true }
edition = { workspace = true }


[dependencies]
tracing = { workspace = true }
calamine = { workspace = true }
convert_case = { workspace = true }
oak-toml = { path = "../../../oaks/examples/oak-toml", features = ["serde"] }
oak-json = { path = "../../../oaks/examples/oak-json" }
pathdiff = { workspace = true }
nargo-template = { workspace = true }
regex = { workspace = true }
twox-hash = { workspace = true }
serde = { workspace = true }
csv = { workspace = true }
#futures = "0.3.17"
tokio = { workspace = true }
integer-encoding = { workspace = true }
# dejavu-core = { path = "../../../dejavu-engine/projects/dejavu-core" }



[dependencies.xcell-core]
workspace = true
features = ["csharp", "typescript", "globset", "notify", "walkdir", "async-walkdir"]

[dependencies.xcell-provider]
workspace = true

[dependencies.xcell-plugin]
workspace = true

[dependencies.xcell-config]
workspace = true

[dependencies.xcell-parser]
workspace = true

[dev-dependencies]
tracing-subscriber = { workspace = true }

[build-dependencies]
peginator = { workspace = true }

[features]
default = []
