[package]
name = "xcell-config"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
serde = { workspace = true }
oak-json = { workspace = true }
oak-toml = { workspace = true, features = ["serde"] }
xcell-core = { workspace = true }
