[workspace]
resolver = "2"
members = ["projects/*"]
default-members = [
    "projects/xcell-errors",
    "projects/xcell-types",
    "projects/xcell-core",
    "projects/xcell-cli",
]
exclude = [
    "projects/.DS_Store",
]

[profile.release]
lto = true
strip = true
panic = "abort"
