version = "0.0.0"
include = "*.xlsx"
exclude = ""
export_conditions = []

[line]
field = 1
type = 2
comment = 3
data = 4

[typing.boolean]
accept = ["true", "√"]
reject = ["false", "x"]
default = false

[typing.string]
patterns = ["str", "string"]
default = ""

[typing.vector]
delimiter = [",", ";"]
suffix = ["[]"]
default = []

[typing.vector.typing.Boolean]
accept = ["true"]
reject = ["false"]
default = false

[typing.language]
group = ["group"]

[typing.enumerate]
name = ""
integer = "Unsigned32"
default = ""

[typing.enumerate.mapping]

[merge]
enable = false

[merge.steps]

[unity.storage.binary]
enable = true
output = "Assets/Tables/Generated"

[unity.storage.json]
enable = false
output = "Assets/Tables/Readable"

[unity.storage.xml]
enable = false
output = "Assets/Tables/Readable"

[unity.storage.protobuf]
enable = false

[unity.loader]
enable = true
project = "../"
output = "Assets/Scripts/DataTable/Generated"
namespace = "DataTable.Generated"
manager = "DataTableManager"
suffix_table = "Table"
suffix_element = "Element"
support_clone = true
legacy_using = false
legacy_null_null = false

[unity.loader.xlua]
enable = false

[cocos.storage.json]
enable = true
output = "assets/tables"

[cocos.loader]
enable = false
project = "../"
output = "assets/scripts/dataTable/generated"
namespace = "DataTable.Generated"
manager_name = "DataTableManager"
suffix_table = "Table"
instance_name = "instance"

[xlua]
enable = false
output = "xlua"
manager_name = "XCellManager"
suffix_table = "Table"
instance_name = "xcell"

[sql]
enable = false
output = "sql"
database = "xcell"

[json]
enable = false
output = ""

[typescript]
enable = false
output = "typescript"
manager_name = "XCellManager"
suffix_table = "Table"
instance_name = "xcell"

[[generators]]
type = "Unity"

[generators.unity.storage.binary]
enable = true
output = "Assets/Tables/Generated"

[generators.unity.storage.json]
enable = false
output = "Assets/Tables/Readable"

[generators.unity.storage.xml]
enable = false
output = "Assets/Tables/Readable"

[generators.unity.storage.protobuf]
enable = false

[generators.unity.loader]
enable = true
project = "../"
output = "Assets/Scripts/DataTable/Generated"
namespace = "DataTable.Generated"
manager = "DataTableManager"
suffix_table = "Table"
suffix_element = "Element"
support_clone = true
legacy_using = false
legacy_null_null = false

[generators.unity.loader.xlua]
enable = false

[generators.cocos.storage.json]
enable = false
output = ""

[generators.cocos.loader]
enable = false
project = ""
output = ""
namespace = ""
manager_name = ""
suffix_table = ""
instance_name = ""

[generators.xlua]
enable = false
output = "xlua"
manager_name = "XCellManager"
suffix_table = "Table"
instance_name = "xcell"

[generators.sql]
enable = false
output = "sql"
database = "xcell"

[generators.json]
enable = false
output = ""

[generators.typescript]
enable = false
output = "typescript"
manager_name = "XCellManager"
suffix_table = "Table"
instance_name = "xcell"

[[generators]]
type = "Cocos"

[generators.unity.storage.binary]
enable = false
output = ""

[generators.unity.storage.json]
enable = false
output = ""

[generators.unity.storage.xml]
enable = false
output = ""

[generators.unity.storage.protobuf]
enable = false

[generators.unity.loader]
enable = false
project = ""
output = ""
namespace = ""
manager = ""
suffix_table = ""
suffix_element = ""
support_clone = false
legacy_using = false
legacy_null_null = false

[generators.unity.loader.xlua]
enable = false

[generators.cocos.storage.json]
enable = true
output = "assets/tables"

[generators.cocos.loader]
enable = true
project = "../"
output = "assets/scripts/dataTable/generated"
namespace = "DataTable.Generated"
manager_name = "DataTableManager"
suffix_table = "Table"
instance_name = "instance"

[generators.xlua]
enable = false
output = "xlua"
manager_name = "XCellManager"
suffix_table = "Table"
instance_name = "xcell"

[generators.sql]
enable = false
output = "sql"
database = "xcell"

[generators.json]
enable = false
output = ""

[generators.typescript]
enable = false
output = "typescript"
manager_name = "XCellManager"
suffix_table = "Table"
instance_name = "xcell"
