version = "0.0.0"

exclude = ""
include = "*.csv"

line.field = 1
line.type = 2
line.comment = 3
line.data = 4

[[generators]]
type = "cocos"
enable = true
project = "."
output = "cocos"

[[generators]]
type = "Unity"
enable = true
project = "."
output = "unity"
namespace = "DataTable"