target = ["unity"]

[type.bool]
"true" = ["true", "√"]
"false" = ["false", "x"]

[type.string]


[unity.csharp]
enable = true
path = ""
namespace = ""
table = "Table"
element = "Element"

[unity.xlua]
enable = false

[unity.xml]
enable = true

[unity.json]
enable = false

[unity.protobuf]
enable = false