[type.bool]
"true" = ["true", "√"]
"false" = ["false", "x"]

[type.string]


[unity]
namespace = "DataTable.Generated"
folder_binary = ""
suffix_table = "Table"
suffix_element = "Element"
support_binary = true
support_clone = true
legacy_using = false
