[package]
name = "xcell-plugin"
version = "0.2.0"
authors = { workspace = true }
description = "XCell plugin system"
repository = "https://github.com/oovm/XCell"
documentation = "https://docs.rs/xcell-plugin"
license = { workspace = true }
edition = { workspace = true }

[dependencies]
tracing = { workspace = true }
serde = { workspace = true }

[dependencies.xcell-core]
workspace = true

[dependencies.xcell-provider]
workspace = true

[dev-dependencies]
tracing-subscriber = { workspace = true }
xcell-analyzer = { workspace = true }

[features]
default = []
