[package]
name = "xcell-core"
version = "0.0.0"
authors = ["Aster <192607617@qq.com>"]
description = "..."
repository = "https://github.com/oovm/XCell"
documentation = "https://docs.rs/sub_projects"
readme = "Readme.md"
license = "MPL-2.0"
edition = "2021"

[dependencies]
calamine = "0.19.1"
lsp-types = "0.93.2"
serde = { version = "1.0.147", features = ["derive"] }
toml = "0.5.9"
num = "0.4.0"
diagnostic = "0.3.9"
xxhash-rust = { version = "0.8.6", features = ["xxh64"] }

[dependencies.sled-typed]
#version = ""
git = "https://github.com/oovm/disk-map"
rev = "0c4cc29b"

[dev-dependencies]
#tokio = { version = "1.21.2", features = ["full"] }

[features]
default = []
