[package]
name = "xcell-core"
publish = false
version = "0.0.0"
authors = ["Aster <192607617@qq.com>"]
description = "..."
repository = "https://github.com/oovm/XCell"
documentation = "https://docs.rs/sub_projects"
readme = "Readme.md"
license = "MPL-2.0"
edition = "2021"

[dependencies]
calamine = "0.19.1"
lsp-types = "0.93.2"
serde = { version = "1.0.147", features = ["derive"] }
toml = "0.5.9"



[dev-dependencies]

[features]
default = []
