[package]
name = "xcell-core"
version = "0.0.0"
authors = ["Aster <192607617@qq.com>"]
description = "..."
repository = "https://github.com/oovm/XCell"
documentation = "https://docs.rs/sub_projects"
readme = "Readme.md"
license = "MPL-2.0"
edition = "2021"

[dependencies]
log = "0.4.17"
calamine = "0.19.1"
toml = "0.5.9"
pathdiff = "0.2.1"
tera = "1.17.1"
diagnostic = "0.3.10"
twox-hash = "1.6.3"
byteorder = "1.4.3"
serde = { version = "1.0.147", features = ["derive"] }
num = { version = "0.4.0", features = ["serde"] }
bigdecimal = { version = "0.3.0", features = ["serde"] }
decimal = { version = "2.1.0", features = ["serde"] }
array2d = { version = "0.2.1", features = ["serde"] }
#ndarray = { version = "0.15.6", features = ["serde"] }
chrono = { version = "0.4.22", features = ["serde"] }
csscolorparser = { version = "0.6.2", features = ["serde"] }

[dependencies.sled-typed]
#version = ""
git = "https://github.com/oovm/disk-map"
rev = "0c4cc29b"

[dev-dependencies]
#tokio = { version = "1.21.2", features = ["full"] }

[features]
default = []
