[package]
name = "xcell-macros"
version = { workspace = true }
authors = { workspace = true }
description = "Macros for xcell"
repository = "https://github.com/oovm/XCell"
documentation = "https://docs.rs/xcell-macros"
license = { workspace = true }
edition = { workspace = true }

[lib]
proc-macro = true

[dependencies]
# Proc macro dependencies
proc-macro2 = { workspace = true }
syn = { workspace = true }
quote = { workspace = true }

# Other dependencies
serde = { workspace = true }
diagnostic = { workspace = true }
validatus = { workspace = true }

[dev-dependencies]

[features]
default = []

[package.metadata.docs.rs]
all-features = true
