[package]
name = "xcell-gui"
version = "0.0.0"
authors = ["Aster <192607617@qq.com>"]
description = "..."
repository = "https://github.com/oovm/XCell"
documentation = "https://docs.rs/sub_projects"
readme = "Readme.md"
license = "MPL-2.0"
edition = "2021"

[dependencies]
iced = "0.10.0"
log = { version = "0.4.20", features = ["std"] }
regex = "1.10.2"

[dev-dependencies]

[features]
default = []
