[package]
name = "xcell"
version = "0.2.0"
authors = ["Aster <192607617@qq.com>"]
description = "XCell command line tool"
repository = "https://github.com/oovm/XCell"
documentation = "https://docs.rs/xcell"
readme = "Readme.md"
license = "MPL-2.0"
edition = "2021"


[dependencies]
#colored = "2.0.0"
time = "0.3.34"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["local-time"] }
chrono = "0.4.34"
clap = { version = "4.5.1", features = ["derive"] }
tokio = { version = "1.36.0", features = ["full"] }

[dependencies.xcell-core]
version = "0.2.0"
path = "../xcell-core"

[dev-dependencies]

[target.'cfg(windows)'.build-dependencies]
winres = "0.1.12"

[package.metadata.winres]
OriginalFilename = "XCell.exe"
LegalCopyright = "Copyright © 2020"

[features]
default = []
