version = "0.0.0"


exclude = """
*.xlsx
"""

include = """
*.xlsx
"""



[type.bool]
"true" = ["true", "√"]
"false" = ["false", "x"]

[type.string]


[unity]
enable = true
namespace = "DataTable.Generated"
manager = "DataTableManager"
suffix_table = "Table"
suffix_element = "Element"
support_clone = true
legacy_using = false
legacy_null_null = false

[unity.binary]
enable = true
output = "Assets/Scripts/DataTable/Generated"

[unity.xlua]
enable = false

[unity.xml]
enable = true

[unity.json]
enable = false

[unity.protobuf]
enable = false