[package]
name = "xcell-core"
version = { workspace = true }
authors = { workspace = true }
description = "Core types and utilities for xcell"
repository = "https://github.com/oovm/XCell"
documentation = "https://docs.rs/xcell-core"
license = { workspace = true }
edition = { workspace = true }

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
itertools = { workspace = true }
vlq-rust = { workspace = true }
diagnostic = { workspace = true }
validatus = { workspace = true }
futures = { workspace = true }
xcell-parser = { workspace = true }
oak-json = { workspace = true, optional = true }
oak-core = { path = "../../../oaks/projects/oak-core" }
num = { workspace = true, optional = true, features = ["serde"] }
bigdecimal = { workspace = true, optional = true, features = ["serde"] }
chrono = { workspace = true, optional = true, features = ["serde"] }
csscolorparser = { workspace = true, optional = true, features = ["serde"] }

[dev-dependencies]

[build-dependencies]

[features]
default = ["num", "bigdecimal", "chrono", "csscolorparser", "oak-json"]

