[package]
name = "xcell-generator"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
edition = { workspace = true }



[dependencies]
xcell-core = { workspace = true }
xcell-provider = { workspace = true }
xcell-analyzer = { workspace = true }
xcell-config = { workspace = true }

# 通用依赖
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
serde = { workspace = true, features = ["derive"] }
oak-toml = { workspace = true, features = ["serde"] }
oak-json = { workspace = true }
convert_case = { workspace = true }
url = { workspace = true }
csv = { workspace = true }
chrono = { workspace = true }

# 代码生成依赖
nargo-template = { workspace = true }
tempfile = { workspace = true }
