[package]
name = "xcell-parser"
version = { workspace = true }
authors = { workspace = true }
description = "Parser for XCell type expressions using parser combinators"
repository = "https://github.com/oovm/XCell"
documentation = "https://docs.rs/xcell-parser"
license = { workspace = true }
edition = { workspace = true }

[dependencies]
serde = { workspace = true }

[dev-dependencies]

[features]
default = []
